disabled_rules:
    - force_cast
    - nesting
    - cyclomatic_complexity
    - file_length
    - type_body_length
    - function_body_length
    - line_length
    - block_based_kvo
    - class_delegate_protocol
